version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=kitchen
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'